### ISSUE TITLE
ESP device sends garbage values

### ISSUE THREAD

**Issue by jkandasa** [mycontroller-org/MyControllerDevice#20]
```
2018-04-23 10:42:52,101 ERROR [mc-th-pool-0] [org.mycontroller.standalone.provider.EngineAbstract:261] Throws exception while processing!, [MessageImpl(gatewayId=1, nodeEui=ESP_49C88D, sensorId=memory, type=Set, subType=Free, ack=0, payload=dsses, isTxMessage=false, timestamp=1524460372098, properties=null)]
java.lang.NumberFormatException: For input string: "dsses"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at java.lang.Double.valueOf(Double.java:502)
	at org.mycontroller.standalone.utils.McUtils.getDouble(McUtils.java:100)
	at org.mycontroller.standalone.utils.McUtils.getDouble(McUtils.java:95)
	at org.mycontroller.standalone.provider.ExecuterAbstract.updateSensorVariable(ExecuterAbstract.java:569)
	at org.mycontroller.standalone.provider.ExecuterAbstract.executeSet(ExecuterAbstract.java:360)
	at org.mycontroller.standalone.provider.ExecuterAbstract.execute(ExecuterAbstract.java:101)
	at org.mycontroller.standalone.provider.EngineAbstract.auditQueue(EngineAbstract.java:256)
	at org.mycontroller.standalone.provider.EngineAbstract.run(EngineAbstract.java:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-04-23 10:43:52,108 ERROR [mc-th-pool-0] [org.mycontroller.standalone.provider.EngineAbstract:261] Throws exception while processing!, [MessageImpl(gatewayId=1, nodeEui=ESP_49C88D, sensorId=memory, type=Set, subType=Free, ack=0, payload=dsses, isTxMessage=false, timestamp=1524460432104, properties=null)]
java.lang.NumberFormatException: For input string: "dsses"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at java.lang.Double.valueOf(Double.java:502)
	at org.mycontroller.standalone.utils.McUtils.getDouble(McUtils.java:100)
	at org.mycontroller.standalone.utils.McUtils.getDouble(McUtils.java:95)
	at org.mycontroller.standalone.provider.ExecuterAbstract.updateSensorVariable(ExecuterAbstract.java:569)
	at org.mycontroller.standalone.provider.ExecuterAbstract.executeSet(ExecuterAbstract.java:360)
	at org.mycontroller.standalone.provider.ExecuterAbstract.execute(ExecuterAbstract.java:101)
	at org.mycontroller.standalone.provider.EngineAbstract.auditQueue(EngineAbstract.java:256)
	at org.mycontroller.standalone.provider.EngineAbstract.run(EngineAbstract.java:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-04-23 10:44:52,058 ERROR [mc-th-pool-0] [org.mycontroller.standalone.provider.EngineAbstract:261] Throws exception while processing!, [MessageImpl(gatewayId=1, nodeEui=ESP_49C88D, sensorId=memory, type=Set, subType=Free, ack=0, payload=dsses, isTxMessage=false, timestamp=1524460492053, properties=null)]
java.lang.NumberFormatException: For input string: "dsses"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at java.lang.Double.valueOf(Double.java:502)
	at org.mycontroller.standalone.utils.McUtils.getDouble(McUtils.java:100)
	at org.mycontroller.standalone.utils.McUtils.getDouble(McUtils.java:95)
	at org.mycontroller.standalone.provider.ExecuterAbstract.updateSensorVariable(ExecuterAbstract.java:569)
	at org.mycontroller.standalone.provider.ExecuterAbstract.executeSet(ExecuterAbstract.java:360)
	at org.mycontroller.standalone.provider.ExecuterAbstract.execute(ExecuterAbstract.java:101)
	at org.mycontroller.standalone.provider.EngineAbstract.auditQueue(EngineAbstract.java:256)
	at org.mycontroller.standalone.provider.EngineAbstract.run(EngineAbstract.java:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-04-23 10:45:52,061 ERROR [mc-th-pool-0] [org.mycontroller.standalone.provider.EngineAbstract:261] Throws exception while processing!, [MessageImpl(gatewayId=1, nodeEui=ESP_49C88D, sensorId=memory, type=Set, subType=Free, ack=0, payload=dsses, isTxMessage=false, timestamp=1524460552034, properties=null)]
java.lang.NumberFormatException: For input string: "dsses"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at java.lang.Double.valueOf(Double.java:502)
	at org.mycontroller.standalone.utils.McUtils.getDouble(McUtils.java:100)
	at org.mycontroller.standalone.utils.McUtils.getDouble(McUtils.java:95)
	at org.mycontroller.standalone.provider.ExecuterAbstract.updateSensorVariable(ExecuterAbstract.java:569)
	at org.mycontroller.standalone.provider.ExecuterAbstract.executeSet(ExecuterAbstract.java:360)
	at org.mycontroller.standalone.provider.ExecuterAbstract.execute(ExecuterAbstract.java:101)
	at org.mycontroller.standalone.provider.EngineAbstract.auditQueue(EngineAbstract.java:256)
	at org.mycontroller.standalone.provider.EngineAbstract.run(EngineAbstract.java:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-04-23 10:46:52,129 ERROR [mc-th-pool-0] [org.mycontroller.standalone.provider.EngineAbstract:261] Throws exception while processing!, [MessageImpl(gatewayId=1, nodeEui=ESP_49C88D, sensorId=memory, type=Set, subType=Free, ack=0, payload=dsses, isTxMessage=false, timestamp=1524460612124, properties=null)]
java.lang.NumberFormatException: For input string: "dsses"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at java.lang.Double.valueOf(Double.java:502)
	at org.mycontroller.standalone.utils.McUtils.getDouble(McUtils.java:100)
	at org.mycontroller.standalone.utils.McUtils.getDouble(McUtils.java:95)
	at org.mycontroller.standalone.provider.ExecuterAbstract.updateSensorVariable(ExecuterAbstract.java:569)
	at org.mycontroller.standalone.provider.ExecuterAbstract.executeSet(ExecuterAbstract.java:360)
	at org.mycontroller.standalone.provider.ExecuterAbstract.execute(ExecuterAbstract.java:101)
	at org.mycontroller.standalone.provider.EngineAbstract.auditQueue(EngineAbstract.java:256)
	at org.mycontroller.standalone.provider.EngineAbstract.run(EngineAbstract.java:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-04-23 10:47:52,139 ERROR [mc-th-pool-0] [org.mycontroller.standalone.provider.EngineAbstract:261] Throws exception while processing!, [MessageImpl(gatewayId=1, nodeEui=ESP_49C88D, sensorId=memory, type=Set, subType=Free, ack=0, payload=dsses, isTxMessage=false, timestamp=1524460672135, properties=null)]
java.lang.NumberFormatException: For input string: "dsses"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at java.lang.Double.valueOf(Double.java:502)
	at org.mycontroller.standalone.utils.McUtils.getDouble(McUtils.java:100)
	at org.mycontroller.standalone.utils.McUtils.getDouble(McUtils.java:95)
	at org.mycontroller.standalone.provider.ExecuterAbstract.updateSensorVariable(ExecuterAbstract.java:569)
	at org.mycontroller.standalone.provider.ExecuterAbstract.executeSet(ExecuterAbstract.java:360)
	at org.mycontroller.standalone.provider.ExecuterAbstract.execute(ExecuterAbstract.java:101)
	at org.mycontroller.standalone.provider.EngineAbstract.auditQueue(EngineAbstract.java:256)
	at org.mycontroller.standalone.provider.EngineAbstract.run(EngineAbstract.java:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-04-23 10:48:52,039 ERROR [mc-th-pool-0] [org.mycontroller.standalone.provider.EngineAbstract:261] Throws exception while processing!, [MessageImpl(gatewayId=1, nodeEui=ESP_49C88D, sensorId=memory, type=Set, subType=Free, ack=0, payload=dsses, isTxMessage=false, timestamp=1524460732036, properties=null)]
java.lang.NumberFormatException: For input string: "dsses"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at java.lang.Double.valueOf(Double.java:502)
	at org.mycontroller.standalone.utils.McUtils.getDouble(McUtils.java:100)
	at org.mycontroller.standalone.utils.McUtils.getDouble(McUtils.java:95)
	at org.mycontroller.standalone.provider.ExecuterAbstract.updateSensorVariable(ExecuterAbstract.java:569)
	at org.mycontroller.standalone.provider.ExecuterAbstract.executeSet(ExecuterAbstract.java:360)
	at org.mycontroller.standalone.provider.ExecuterAbstract.execute(ExecuterAbstract.java:101)
	at org.mycontroller.standalone.provider.EngineAbstract.auditQueue(EngineAbstract.java:256)
	at org.mycontroller.standalone.provider.EngineAbstract.run(EngineAbstract.java:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-04-23 10:49:52,155 ERROR [mc-th-pool-0] [org.mycontroller.standalone.provider.EngineAbstract:261] Throws exception while processing!, [MessageImpl(gatewayId=1, nodeEui=ESP_49C88D, sensorId=memory, type=Set, subType=Free, ack=0, payload=dsses, isTxMessage=false, timestamp=1524460792150, properties=null)]
java.lang.NumberFormatException: For input string: "dsses"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at java.lang.Double.valueOf(Double.java:502)
	at org.mycontroller.standalone.utils.McUtils.getDouble(McUtils.java:100)
	at org.mycontroller.standalone.utils.McUtils.getDouble(McUtils.java:95)
	at org.mycontroller.standalone.provider.ExecuterAbstract.updateSensorVariable(ExecuterAbstract.java:569)
	at org.mycontroller.standalone.provider.ExecuterAbstract.executeSet(ExecuterAbstract.java:360)
	at org.mycontroller.standalone.provider.ExecuterAbstract.execute(ExecuterAbstract.java:101)
	at org.mycontroller.standalone.provider.EngineAbstract.auditQueue(EngineAbstract.java:256)
	at org.mycontroller.standalone.provider.EngineAbstract.run(EngineAbstract.java:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jkandasa** [comment]
Workaround: Do compile with ESP 8266 community version: 2.3.0
